### ISSUE TITLE
git HEAD is throwing an exception and does not open the editor

### ISSUE THREAD

**Issue by userxfce** [RustDT/RustDT#10]
---
## STATUS

pluginId:           org.eclipse.ui.workbench.texteditor
pluginVersion:      3.9.100.v20141023-1946
code:               0
severity:           4
message:            HIDDEN
fingerprint:        e47e7207

Exception:java.lang.NoSuchMethodError: HIDDEN
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at org.eclipse.ui.texteditor.AbstractTextEditor$19.run(AbstractTextEditor.java:3220)
     at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
     at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
     at org.eclipse.ui.internal.WorkbenchWindow$13.run(WorkbenchWindow.java:2138)
     at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
     at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2134)
     at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3238)
     at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3265)
     at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:366)
     at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:313)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
     at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:888)
     at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:869)
     at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:120)
     at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:337)
     at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:258)
     at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
     at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
     at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
     at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
     at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:128)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:983)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:766)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:737)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:731)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:715)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:96)
     at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
     at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:187)
     at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
     at org.eclipse.swt.widgets.Display.syncExec(Display.java:4634)
     at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
     at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
     at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
     at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
     at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
     at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
     at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
     at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
     at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
     at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
     at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
     at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
     at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
     at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
     at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:488)
     at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:454)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:715)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:393)
     at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1151)
     at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3185)
     at org.eclipse.ui.internal.WorkbenchPage.access$24(WorkbenchPage.java:3100)
     at org.eclipse.ui.internal.WorkbenchPage$9.run(WorkbenchPage.java:3082)
     at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
     at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3077)
     at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3041)
     at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3031)
     at org.eclipse.ui.ide.IDE.openEditor(IDE.java:541)
     at org.eclipse.ui.ide.IDE.openEditor(IDE.java:500)
     at org.eclipse.ui.actions.OpenFileAction.openFile(OpenFileAction.java:100)
     at org.eclipse.ui.actions.OpenSystemEditorAction.run(OpenSystemEditorAction.java:100)
     at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:229)
     at org.eclipse.ui.navigator.CommonNavigatorManager$2.open(CommonNavigatorManager.java:191)
     at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
     at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:854)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
     at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
     at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:851)
     at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1168)
     at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:449)
     at org.eclipse.jface.viewers.StructuredViewer$6.handleOpen(StructuredViewer.java:1275)
     at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:278)
     at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:272)
     at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:313)
     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4480)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1413)
     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3818)
     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3428)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:648)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:592)
     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
     at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
     at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by bruno-medeiros** [comment]
Things are working fine here. That looks like some setup error on your side. If you still get the same error, I need more info on how you setup Eclipse, and how you are starting it.
