### ISSUE TITLE
"IllegalStateException: Invalid table definition" during Cargo manifest parsing

### ISSUE THREAD

**Issue by HighCommander4** [RustDT/RustDT#129]
I am using RustDT to edit the source of [rustfmt](https://github.com/rust-lang-nursery/rustfmt), and I often get a notification about the following exception:

```
java.lang.IllegalStateException: Invalid table definition on line 35: [target.'cfg(unix)'.dependencies]]
  at com.moandjiezana.toml.Toml.read(Toml.java:122)                                  
  at com.github.rustdt.tooling.cargo.CargoManifestParser.parse(CargoManifestParser.java:37)
  at com.github.rustdt.ide.core.cargomodel.RustBundleModelManager.createNewInfo(RustBundleModelManager.java:64)
  at melnorme.lang.ide.core.project_model.BundleModelManager.handleBundleProjectAdded(BundleModelManager.java:107)
  at melnorme.lang.ide.core.project_model.BundleModelManager.bundleProjectAdded(BundleModelManager.java:103)
  at melnorme.lang.ide.core.project_model.ProjectBasedModelManager$ManagerResourceListener.bundleProjectAdded(ProjectBasedModelManager.java:71)
  at melnorme.lang.ide.core.project_model.BundleManifestResourceListener.tentativeAddBundleProject(BundleManifestResourceListener.java:71)
  at melnorme.lang.ide.core.project_model.BundleManifestResourceListener.processProjectDelta(BundleManifestResourceListener.java:54)
  at melnorme.lang.ide.core.utils.DefaultProjectResourceListener.processWorkspaceDelta(DefaultProjectResourceListener.java:35)
  at melnorme.lang.ide.core.utils.DefaultProjectResourceListener.resourceChanged(DefaultProjectResourceListener.java:30)
  at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
  at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)                     
  at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
  at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
  at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
  at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2253)     
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)     
  at melnorme.lang.ide.core.engine.ProblemMarkerUpdater$UpdateProblemMarkersTask.updateProblemMarkers(ProblemMarkerUpdater.java:126)
  at melnorme.lang.ide.core.engine.ProblemMarkerUpdater$UpdateProblemMarkersTask.run(ProblemMarkerUpdater.java:102)
  at melnorme.utilbox.concurrency.ICommonExecutor.lambda$0(ICommonExecutor.java:44)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)                        
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)                    
```

The line it seems to choke on is [this one](https://github.com/rust-lang-nursery/rustfmt/blob/5361f61/Cargo.toml#L35).

**Comment by bruno-medeiros** [comment]
Opened https://github.com/mwanji/toml4j/issues/36
