### ISSUE TITLE
Failed to launch project

### ISSUE THREAD

**Issue by fbecart** [RustDT/RustDT#13]
I'm following the instructions to set up and use RustDT. I successfully added RustDT to a clean Eclipse installation.

I just installed Rust, I don't know where it's actually located on my system. In the Rust Preferences, I set `/usr/local` as a Rust Installation Directory.

![Rust Preferences](https://cloud.githubusercontent.com/assets/763541/6880635/ca21576a-d53c-11e4-8223-c3611f35e48a.png)

I created a project and a run configuration.

![Run Configuration](https://cloud.githubusercontent.com/assets/763541/6880631/a9aabc2e-d53c-11e4-889b-31fc56fd69d3.png)

The console indicates correctly the result of the build. However, when I hit 'Run', I get this error popup indicating:

```
Failed to create a child process.
Cannot run program "<...>/hello-world/src/main.rs" (in directory "<...>/hello-world"): error=13, Permission denied
```

I hope you can have a look at it. Please let me know if you need additional information

Installation details:
- RustDT 0.1.0.v201502251513
- rustc 1.0.0-nightly (199bdcfef 2015-03-26)
- Eclipse Platform 4.4.2.M20150204-1700
- Mac OS X 10.10.2

Here is the stacktrace appearing in the error logs

```
!ENTRY com.github.rustdt.ide.core 4 101 2015-03-28 11:24:15.178
!MESSAGE Failed to create a child process.
!STACK 0
java.io.IOException: Cannot run program "<...>/hello-world/src/main.rs" (in directory "<...>/hello-world"): error=13, Permission denied
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
    at melnorme.lang.ide.launching.EclipseProcessLauncher.newSystemProcess(EclipseProcessLauncher.java:94)
    at melnorme.lang.ide.launching.EclipseProcessLauncher.launchProcess(EclipseProcessLauncher.java:79)
    at melnorme.lang.ide.launching.AbstractLangLaunchConfigurationDelegate.launchProcess(AbstractLangLaunchConfigurationDelegate.java:264)
    at melnorme.lang.ide.launching.AbstractLangLaunchConfigurationDelegate.launch(AbstractLangLaunchConfigurationDelegate.java:161)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.IOException: error=13, Permission denied
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:185)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
    ... 9 more
```

**Comment by bruno-medeiros** [comment]
Program Path is the path to the created executable, not to Rust source.

**Comment by fbecart** [comment]
Thanks Bruno, it worked like a charm! Keep up with the good work :)
