### ISSUE TITLE
The `No build targets available for project.` error for all the projects in the workspace.

### ISSUE THREAD

**Issue by snuk182** [RustDT/RustDT#161]
Happened all of a sudden, both for Kubuntu 16.04 & Windows 10, x64.
~~Workaround: close & open each of the projects *distinctly*~~ does not help anymore.
Entering Project Properties - Build Targets errors out, no items in Build Targets combo box.

**Comment by bruno-medeiros** [comment]
Can you provide the error log, see if there is some more info there? I can't see what would be causing this error.

**Comment by snuk182** [comment]
Please try this https://drive.google.com/file/d/0B9pTuZFIK_uWbU9GNXRVR1paV2M/view?usp=sharing

**Comment by snuk182** [comment]
Here is the part from the linux workspace log. 
What is interesting, the Windows workspace does not have this, but still if I close the project with Cargo.toml containing this, the workspace becomes sane again.
```
!ENTRY org.eclipse.core.resources 4 2 2017-04-28 18:41:30.221
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.IllegalStateException: Invalid table definition on line 16: [target.'cfg(target_os = "windows")'.dependencies]]
	at com.moandjiezana.toml.Toml.read(Toml.java:140)
	at com.github.rustdt.tooling.cargo.CargoManifestParser.parse(CargoManifestParser.java:37)
	at com.github.rustdt.ide.core.cargomodel.RustBundleModelManager.createNewInfo(RustBundleModelManager.java:64)
	at melnorme.lang.ide.core.project_model.BundleModelManager.handleBundleProjectAdded(BundleModelManager.java:107)
	at melnorme.lang.ide.core.project_model.BundleModelManager.bundleProjectAdded(BundleModelManager.java:103)
	at melnorme.lang.ide.core.project_model.BundleModelManager.bundleManifestFileChanged(BundleModelManager.java:95)
	at melnorme.lang.ide.core.project_model.ProjectBasedModelManager$ManagerResourceListener.bundleManifestChanged(ProjectBasedModelManager.java:81)
	at melnorme.lang.ide.core.project_model.BundleManifestResourceListener.processProjectDelta(BundleManifestResourceListener.java:63)
	at melnorme.lang.ide.core.utils.DefaultProjectResourceListener.processWorkspaceDelta(DefaultProjectResourceListener.java:35)
	at melnorme.lang.ide.core.utils.DefaultProjectResourceListener.resourceChanged(DefaultProjectResourceListener.java:30)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:46)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)```

**Comment by snuk182** [comment]
Copy of https://github.com/RustDT/RustDT/issues/129 , closing. Thanks for the attention!

**Comment by snuk182** [comment]
https://github.com/mwanji/toml4j/issues/33 Original ticket.
