### ISSUE TITLE
Master branch tests failed

### ISSUE THREAD

**Issue by leonidv** [RustDT/RustDT#164]
I try to make mvn clean verify in just downloaded master branch. Build is broken by failed tests with common error:

```
melnorme.lang.ide.core.text.TextSourceUtil_Test  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class melnorme.lang.ide.core.tests.CommonCoreTest
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
```

Full logs: https://gist.github.com/leonidv/29e06233a253b2b2a211bbf268afa67c
mvn info:
```
> mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T22:39:06+03:00)
Maven home: D:\apps\apache-maven-3.5.0\bin\..
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jre1.8.0_121
Default locale: ru_RU, platform encoding: Cp1251
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by bruno-medeiros** [comment]
Well, that is odd, the build on Travis CI works fine: https://travis-ci.org/RustDT/RustDT/builds/213485343
and also on my local machine.

**Comment by leonidv** [comment]
I see Travis executes test on Debian. I try to run on Windows. What OS do you use? There can be a matter in OS specifics steps?

**Comment by bruno-medeiros** [comment]
I use Windows 10 too, and it works here. BTW, there is the core of the error:

```
Caused by: melnorme.utilbox.core.Assert$AssertFailedException: null
	at melnorme.utilbox.core.Assert$AssertHandler.handleAssert(Assert.java:62)
	at melnorme.utilbox.core.Assert.checkAssertion(Assert.java:94)
	at melnorme.utilbox.core.Assert$AssertNamespace.assertFail(Assert.java:190)
	at melnorme.lang.ide.core.tests.CommonCoreTest.initializeWorkingDirToEclipseInstanceLocation(CommonCoreTest.java:136)
	at melnorme.lang.ide.core.tests.CommonCoreTest.<clinit>(CommonCoreTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

In class `initializeWorkingDirToEclipseInstanceLocation`. Is there something odd about the directory you placed the source and are running Maven from? Maybe it has non-ascii characters?
